---
- hosts: tag_GW_TomcatVersion_7_Latest
  user: ec2-user
  become: True
  tasks:
  - name: copy-install-appdynamics-script
    copy: 
     src: install-appdynamics.sh
     dest: /home/ec2-user/install-appdynamics.sh
     owner: ec2-user
     group: ec2-user
     mode: 0750
  - name: Run install script
    shell: sudo /home/ec2-user/install-appdynamics.sh 

