---
- hosts: tag_GW_JavaVersion_1_7_Latest
  user: ec2-user
  sudo: yes
  tasks:
  - name: Install openjava_1.7
    yum:
      name: java-1.7.0-openjdk 
      state: present
  - name: Set default Java version
    shell: /usr/sbin/alternatives --set java  /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.201-2.6.16.1.el7_6.x86_64/jre/bin/java
