---
- hosts: tag_GW_JavaVersion_1_8_Latest
  user: ec2-user
  sudo: yes
  tasks:
  - name: Install openjava_1.8
    yum:
      name: java-1.8.0-openjdk 
      state: present
  - name: Set default Java version
    shell: /usr/sbin/alternatives --set java   /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/bin/java

